### ISSUE TITLE
PylonTech API documentation

### ISSUE THREAD

**Issue by psjuan97** [celsworth/lxp-pylon-utils#2]
Hi

I'm interested in programing over the PylonTech communication protocol. Can you share your documentation api for the RS232/485 protocols . 

Thanks!

**Comment by celsworth** [comment]
Sure! I've added it to this repository: https://github.com/celsworth/lxp-pylon-utils/blob/master/doc/PYLON%20LFP%20Battery%20communication%20protocol%20-%20RS232%20V2.8%2020161216.pdf
