### ISSUE TITLE
Error reading input register, discharge_power

### ISSUE THREAD

**Issue by mark-sch** [celsworth/lxp-pylon-utils#4]
Hi, awesome work / reverse engineering. The automatically pushed Readinput1-3 is received and parsed fine, but a custom request for an input register gives no response/result. Does the current code work for you? I am testing with LXP 4.6 hybrid inverter.

ruby lxp_ctl.rb discharge_power
Sending = #<LXP::Packet::WriteSingle:0x000056305b6b6b60>
IN: [161, 26, 2, 0, 13, 0, 1, 193, 66, 65, 49, 57, 53, 50, 48, 49, 55, 54, 0]
Result = 
Result data: {}
IN: [161, 26, 2, 0, 111, 0, 1, 194, 66, 65, 49, 57, 53, 50, 48, 49, 55, 54, 97, 0, 1, 4, 48, 49, 48, 50, 48, 48, 52, 48, 55, 56, 0, 0, 80, 4, 0, 101, 12, 34, 12, 2, 0, 9, 2, 100, 0, 0, 28, 252, 2, 250, 2, 0, 0, 0, 0, 0, 0, 48, 9, 1, 1, 0, 0, 135, 19, 216, 5, 0, 0, 137, 2, 232, 3, 48, 9, 211, 171, 9, 0, 135, 19, 0, 0, 0, 0, 200, 4, 0, 0, 114, 0, 113, 0, 0, 0, 188, 0, 0, 0, 67, 0, 32, 0, 0, 0, 30, 0, 0, 0, 116, 14, 0, 13, 167, 39]
Result = #<LXP::Packet::ReadInput1:0x000056305b6b47c0>
Result data: {"status":4,"v_bat":52.1,"soc":100,"p_pv":764,"p_charge":0,"p_discharge":0,"v_acr":235.2,"f_ac":49.99,"p_inv":1496,"p_rec":0,"v_eps":235.2,"f_eps":49.99,"p_to_grid":200,"p_to_user":1024,"e_pv_day":11.4,"e_inv_day":18.8,"e_rec_day":0.0,"e_chg_day":6.7,"e_dischg_day":3.2,"e_eps_day":0.0,"e_to_grid_day":3.0,"e_to_user_day":0.0,"v_bus_1":370.0,"v_bus_2":332.8}
IN: [161, 26, 2, 0, 111, 0, 1, 194, 66, 65, 49, 57, 53, 50, 48, 49, 55, 54, 97, 0, 1, 4, 48, 49, 48, 50, 48, 48, 52, 48, 55, 56, 40, 0, 80, 247, 43, 0, 0, 254, 29, 0, 0, 0, 0, 0, 0, 212, 70, 0, 0, 1, 0, 0, 0, 247, 17, 0, 0, 244, 15, 0, 0, 0, 0, 0, 0, 119, 19, 0, 0, 199, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 51, 0, 40, 0, 43, 0, 0, 0, 1, 0, 195, 106, 97, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 10, 0, 54, 12, 99, 245]
Result = #<LXP::Packet::ReadInput2:0x000056305b6a8ab0>
Result data: {"e_pv_all":1125.5,"e_inv_all":1813.2,"e_rec_all":0.1,"e_chg_all":459.9,"e_dischg_all":408.4,"e_eps_all":0.0,"e_to_grid_all":498.3,"e_to_user_all":45.5,"t_inner":51,"t_rad_1":40,"t_rad_2":43}
IN: [161, 26, 2, 0, 111, 0, 1, 194, 66, 65, 49, 57, 53, 50, 48, 49, 55, 54, 97, 0, 1, 4, 48, 49, 48, 50, 48, 48, 52, 48, 55, 56, 80, 0, 80, 10, 1, 220, 5, 76, 29, 21, 2, 214, 1, 1, 0, 12, 0, 8, 0, 0, 0, 0, 0, 192, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 3, 0, 150, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 253, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 48, 49, 48, 50, 48, 48, 52, 48, 55, 56, 33, 133]
Result = #<LXP::Packet::ReadInput3:0x000056305b69e088>
Result data: {"max_chg_curr":15.0,"max_dischg_curr":75.0,"charge_volt_ref":53.3,"dischg_cut_volt":47.0,"bat_status_0":1,"bat_status_1":12,"bat_status_2":8,"bat_status_3":0,"bat_status_4":0,"bat_status_5":192,"bat_status_6":0,"bat_status_7":0,"bat_status_8":0,"bat_status_9":0,"bat_status_inv":3}
^CTraceback (most recent call last):
	3: from lxp_ctl.rb:50:in `<main>'
	2: from lxp_ctl.rb:50:in `loop'
	1: from lxp_ctl.rb:51:in `block in <main>'
lxp_ctl.rb:51:in `recvfrom': Interrupt

**Comment by celsworth** [comment]
Hi!

I'm currently without inverter as I've recently moved and can't set it up again in my rented house currently :(

But last I tried, the code certainly was working and it hasn't really changed recently.

The only thing that comes to mind if you're not getting a response is to double-check your inverter and datalog serial are correctly setup in the configuration file. The easiest place to get them is probably the LXP Web Portal - http://server.luxpowertek.com/WManage/web/config/inverter

If those are right then I've always gotten *some* sort of response when sending it a packet, even if its just to say the inverter didn't understand it. That first packet you see there is just a heartbeat by the way, identified by the 193 - they're listed at https://github.com/celsworth/lxp-packet/blob/master/lib/lxp/packet/tcp_functions.rb

**Comment by mark-sch** [comment]
Hi celsworth,

thanks for your valueable ideas. Unfortunately the inverter does not respond to any command when both serial numbers are correct, neither ReadHold nor ReadInput, so I expect there has been something changed in the protocol. However, the automatically published ReadInput1-3 data can be parsed fine. All data needed is contained but it is publishing new data only every 30secs.
I am not Mr. Ruby unfortunately, so I did further testing in Node.js and put a socket proxy in between for comparison. In your Ruby code I added 
puts "Sending = #{pkt.to_bin.unpack('H*')}"
and compared the hex data being send to the inverter. There is a one byte length difference when comparing with read commands coming from the lux server.
Did you manage to change to auto update interval of ReadInput1-3 or did you simply fire a ReadInput command as often as needed for up to date data?

**Comment by mark-sch** [comment]
Little update: Your documentation was just perfekt, especially with the modbus-crc16 part. Parsing and modifiying an existing (working)request from lux portal worked fine, you can request e.g. ReadInput1 once per second now. I assume there are protocol v1 and v2 differences, I am using the Hybrid-Inverter and not the AC inverter/charger version. Hope you can use your great inverter soon again. Best wishes

**Comment by celsworth** [comment]
Glad you got it working!

I was just about getting more frequent ReadInput1 working before I had to pack my inverter away, I thought I got it working but maybe they changed something in protocol v2.

If there's any code changes to make for protocol v2 I'll try and update this library once I can test it with a working inverter again. If you can leave a note about which parts you had to modify to get it working that would be a good start for me to work on :)
